import OneAndAHalfJohnson.Amplification
import OneAndAHalfJohnson.AmplificationAssembly
import OneAndAHalfJohnson.AmplificationLimits
import OneAndAHalfJohnson.AmplificationParameters
import OneAndAHalfJohnson.AmplificationSize
import OneAndAHalfJohnson.AsymptoticConstruction
import OneAndAHalfJohnson.AsymptoticSizing
import OneAndAHalfJohnson.BaseCardinality
import OneAndAHalfJohnson.BaseConstruction
import OneAndAHalfJohnson.BaseWeightBounds
import OneAndAHalfJohnson.Basic
import OneAndAHalfJohnson.BernoulliChernoff
import OneAndAHalfJohnson.CodeCompletion
import OneAndAHalfJohnson.CodeDistance
import OneAndAHalfJohnson.CompletionParameters
import OneAndAHalfJohnson.ConcreteAnalyticBounds
import OneAndAHalfJohnson.ConcreteArithmetic
import OneAndAHalfJohnson.ConcreteBase
import OneAndAHalfJohnson.ConcreteCompletion
import OneAndAHalfJohnson.ConcreteConstruction
import OneAndAHalfJohnson.ConcreteDivergenceBounds
import OneAndAHalfJohnson.ConcreteFailureSums
import OneAndAHalfJohnson.ConcreteLayerCounting
import OneAndAHalfJohnson.ConcreteLayerDerivative
import OneAndAHalfJohnson.ConcreteLogBounds
import OneAndAHalfJohnson.ConcreteProbabilityCalculus
import OneAndAHalfJohnson.ConcreteSampling
import OneAndAHalfJohnson.ConcreteSyndrome
import OneAndAHalfJohnson.ConcreteTailEnvelopes
import OneAndAHalfJohnson.CoordinateTransport
import OneAndAHalfJohnson.FieldSizing
import OneAndAHalfJohnson.FieldTowerSizing
import OneAndAHalfJohnson.FiniteSyndrome
import OneAndAHalfJohnson.Geometry
import OneAndAHalfJohnson.GeometryCardinality
import OneAndAHalfJohnson.GeometryIndependence
import OneAndAHalfJohnson.GeometryShortening
import OneAndAHalfJohnson.GeometryShorteningBounds
import OneAndAHalfJohnson.GeometryTriple
import OneAndAHalfJohnson.Incidence
import OneAndAHalfJohnson.IncidenceRankBound
import OneAndAHalfJohnson.KernelWitness
import OneAndAHalfJohnson.LayerUnionBound
import OneAndAHalfJohnson.MainTheorems.BaseConstruction
import OneAndAHalfJohnson.MainTheorems.Concrete
import OneAndAHalfJohnson.MainTheorems.Main
import OneAndAHalfJohnson.MainTheorems.Shortening
import OneAndAHalfJohnson.MainTheorems.SyndromeSeparation
import OneAndAHalfJohnson.NumericLogCertificates
import OneAndAHalfJohnson.RandomAmplification
import OneAndAHalfJohnson.RandomFunctional
import OneAndAHalfJohnson.RandomSampling
import OneAndAHalfJohnson.RefinedRandomAmplification
import OneAndAHalfJohnson.ScalarExtension
import OneAndAHalfJohnson.Shortening
import OneAndAHalfJohnson.SubfieldLines
import OneAndAHalfJohnson.SubfieldReduction
import OneAndAHalfJohnson.SubspacePolynomial
import OneAndAHalfJohnson.SubspacePolynomialMoments
import OneAndAHalfJohnson.SubspacePolynomialSeparable
import OneAndAHalfJohnson.SubspacePolynomialShape
import OneAndAHalfJohnson.Supercode
import OneAndAHalfJohnson.Syndrome
import OneAndAHalfJohnson.SyndromeConstruction
import OneAndAHalfJohnson.SyndromeDirections
import OneAndAHalfJohnson.Targets.Base
import OneAndAHalfJohnson.Targets.Conditional
import OneAndAHalfJohnson.Targets.External
import OneAndAHalfJohnson.Targets.Main
import OneAndAHalfJohnson.Thresholds
import OneAndAHalfJohnson.UniformConcentration
import OneAndAHalfJohnson.WeightLayerBounds

#print axioms OneAndAHalfJohnson.relativeWeight
#print axioms OneAndAHalfJohnson.relativeWeight_le_one
#print axioms OneAndAHalfJohnson.far_image_of_uniform_amplification
#print axioms OneAndAHalfJohnson.close_image_of_uniform_amplification
#print axioms OneAndAHalfJohnson.exceptional_count_image_of_uniform_amplification
#print axioms OneAndAHalfJohnson.injective_on_code_of_uniform_amplification
#print axioms OneAndAHalfJohnson.exists_minimum_weight_word
#print axioms OneAndAHalfJohnson.relativeDistance_le_relativeWeight
#print axioms OneAndAHalfJohnson.image_distance_of_uniform_amplification
#print axioms OneAndAHalfJohnson.image_distance_bounds_of_uniform_amplification
#print axioms OneAndAHalfJohnson.Close.exists_relativeWeight_difference
#print axioms OneAndAHalfJohnson.amplified_image_parameters
#print axioms OneAndAHalfJohnson.exists_relative_nearMDS_completion
#print axioms OneAndAHalfJohnson.tendsto_amplify_floor
#print axioms OneAndAHalfJohnson.exists_distance_overshoot
#print axioms OneAndAHalfJohnson.tendsto_amplify_floor_div
#print axioms OneAndAHalfJohnson.exists_left_positive_of_continuousAt
#print axioms OneAndAHalfJohnson.amplificationScale
#print axioms OneAndAHalfJohnson.amplificationScale_pos
#print axioms OneAndAHalfJohnson.amplificationScale_endpoints
#print axioms OneAndAHalfJohnson.exists_amplification_parameters
#print axioms OneAndAHalfJohnson.amplificationSizeConstant
#print axioms OneAndAHalfJohnson.family_card_le_exp_of_dimension_bound
#print axioms OneAndAHalfJohnson.hoeffding_union_lt_one_of_polynomial_length
#print axioms OneAndAHalfJohnson.amplificationSizeConstant_pos
#print axioms OneAndAHalfJohnson.exists_polynomial_hoeffding_threshold
#print axioms OneAndAHalfJohnson.amplify_mem_Icc
#print axioms OneAndAHalfJohnson.amplification_error_le_add_inv
#print axioms OneAndAHalfJohnson.MainTheorems.asymptotic_code_at_size
#print axioms OneAndAHalfJohnson.exists_final_size_threshold
#print axioms OneAndAHalfJohnson.Geometry.codimTwo_card_lt_syndrome_card
#print axioms OneAndAHalfJohnson.Geometry.syndrome_card_le_four_mul_count_mul_qpow
#print axioms OneAndAHalfJohnson.Geometry.codimTwo_card_fraction
#print axioms OneAndAHalfJohnson.BaseConstruction.pair_span_kernel_exclusion
#print axioms OneAndAHalfJohnson.BaseConstruction.surjective_restriction_of_pair
#print axioms OneAndAHalfJohnson.BaseConstruction.exists_unused_slope
#print axioms OneAndAHalfJohnson.BaseConstruction.singleton_syndrome_ne_vertical
#print axioms OneAndAHalfJohnson.BaseConstruction.singleton_syndrome_ne_affine
#print axioms OneAndAHalfJohnson.BaseConstruction.card_exceptional_ge_of_offset_slopes
#print axioms OneAndAHalfJohnson.BaseConstruction.extended_small_word_pair
#print axioms OneAndAHalfJohnson.BaseConstruction.extended_small_word_singleton
#print axioms OneAndAHalfJohnson.BaseWeightBounds.parameter_identities
#print axioms OneAndAHalfJohnson.BaseWeightBounds.cleared_bounds
#print axioms OneAndAHalfJohnson.BaseWeightBounds.normalized_bounds
#print axioms OneAndAHalfJohnson.BaseWeightBounds.normalized_unit_interval
#print axioms OneAndAHalfJohnson.Close
#print axioms OneAndAHalfJohnson.Far
#print axioms OneAndAHalfJohnson.exceptional
#print axioms OneAndAHalfJohnson.relativeDistance
#print axioms OneAndAHalfJohnson.rate
#print axioms OneAndAHalfJohnson.johnson
#print axioms OneAndAHalfJohnson.gamma
#print axioms OneAndAHalfJohnson.amplify
#print axioms OneAndAHalfJohnson.Close.mono
#print axioms OneAndAHalfJohnson.Far.not_close
#print axioms OneAndAHalfJohnson.mem_exceptional
#print axioms OneAndAHalfJohnson.exceptional_mono
#print axioms OneAndAHalfJohnson.bernoulliKL
#print axioms OneAndAHalfJohnson.bernoulliTilt
#print axioms OneAndAHalfJohnson.bernoulli_tilt_identity
#print axioms OneAndAHalfJohnson.bernoulliTilt_nonpos
#print axioms OneAndAHalfJohnson.bernoulliTilt_nonneg
#print axioms OneAndAHalfJohnson.integrable_exp_mul_of_zero_one
#print axioms OneAndAHalfJohnson.mgf_of_zero_one
#print axioms OneAndAHalfJohnson.mgf_sum_zero_one
#print axioms OneAndAHalfJohnson.bernoulli_sum_lower_tail
#print axioms OneAndAHalfJohnson.bernoulli_sum_upper_tail
#print axioms OneAndAHalfJohnson.card_hamming_ball_le
#print axioms OneAndAHalfJohnson.exists_code_completion_of_weight_bounds
#print axioms OneAndAHalfJohnson.exists_code_completion
#print axioms OneAndAHalfJohnson.code_distance_gt_of_nonzero_weights
#print axioms OneAndAHalfJohnson.code_distance_le_of_nonzero_word
#print axioms OneAndAHalfJohnson.syndrome_kernel_distance_gt
#print axioms OneAndAHalfJohnson.syndrome_nonzero_of_pair_span_classification
#print axioms OneAndAHalfJohnson.syndrome_kernel_distance_gt_of_pair_span_classification
#print axioms OneAndAHalfJohnson.completion_cardinality_of_defect_power
#print axioms OneAndAHalfJohnson.singletonDefect
#print axioms OneAndAHalfJohnson.singletonDefect_balance
#print axioms OneAndAHalfJohnson.exists_completion_defect_eq_min
#print axioms OneAndAHalfJohnson.exists_completion_defect_le
#print axioms OneAndAHalfJohnson.rate_eq_one_sub_distance_add_defect
#print axioms OneAndAHalfJohnson.rate_error_le_of_defect_le
#print axioms OneAndAHalfJohnson.completion_defect_power_of_exponent_bound
#print axioms OneAndAHalfJohnson.concrete_completion_exponent
#print axioms OneAndAHalfJohnson.concrete_completion_defect_power
#print axioms OneAndAHalfJohnson.asymptoticCompletionDefect
#print axioms OneAndAHalfJohnson.asymptoticCompletionDefect_exponent
#print axioms OneAndAHalfJohnson.asymptoticCompletionDefect_power
#print axioms OneAndAHalfJohnson.asymptoticCompletionDefect_rate_bound
#print axioms OneAndAHalfJohnson.exists_completion_rate_error_le_six_div
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.rowProbability
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.mul_interval
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.square_interval
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.probability_e
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.probability_wstar
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.probability_d0
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.probability_d1
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.probability_W
#print axioms OneAndAHalfJohnson.ConcreteArithmetic.raw_length
#print axioms OneAndAHalfJohnson.ConcreteArithmetic.incidence_weight
#print axioms OneAndAHalfJohnson.ConcreteArithmetic.distance_cutoffs
#print axioms OneAndAHalfJohnson.ConcreteArithmetic.incidence_count
#print axioms OneAndAHalfJohnson.ConcreteArithmetic.exceptional_count_gap
#print axioms OneAndAHalfJohnson.ConcreteArithmetic.unused_directions_cardinality
#print axioms OneAndAHalfJohnson.ConcreteArithmetic.syndrome_union_bound
#print axioms OneAndAHalfJohnson.ConcreteArithmetic.integral_coset_cutoff
#print axioms OneAndAHalfJohnson.ConcreteArithmetic.completion_defect
#print axioms OneAndAHalfJohnson.ConcreteArithmetic.shortening_transition
#print axioms OneAndAHalfJohnson.ConcreteArithmetic.completion_room
#print axioms OneAndAHalfJohnson.ConcreteArithmetic.completion_rate_identity
#print axioms OneAndAHalfJohnson.ConcreteArithmetic.rate_interval
#print axioms OneAndAHalfJohnson.ConcreteArithmetic.radius_gap
#print axioms OneAndAHalfJohnson.ConcreteArithmetic.coset_completion_separation
#print axioms OneAndAHalfJohnson.ConcreteArithmetic.hamada_matrix_trace
#print axioms OneAndAHalfJohnson.concrete_base_of_AD21_Hamada
#print axioms OneAndAHalfJohnson.exists_concrete_completion
#print axioms OneAndAHalfJohnson.concrete_code_of_sampled_bounds
#print axioms OneAndAHalfJohnson.concrete_code_consequences
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.divergence_lower
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.divergence_alpha_d0
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.divergence_beta_wstar
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.divergence_alpha_W
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.divergence_beta_W
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.divergence_tau_e
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.divergence_delta_d1
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.count_d0_upper
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.count_wstar_upper
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.count_global_upper
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.log_q_upper
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.survival_W_lower
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.finite_field_correction_lower
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.derivative_envelope_lower
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.derivative_alpha_lower
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.derivative_beta_first_lower
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.derivative_beta_second_lower
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.log_derivative_alpha_upper
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.log_derivative_beta_upper
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.log_exceptional_count_upper
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.probability_d0_lower
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.probability_wstar_lower
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.coarse_failure_budget
#print axioms OneAndAHalfJohnson.family_tail_sum_le
#print axioms OneAndAHalfJohnson.nonzeroCodeWords
#print axioms OneAndAHalfJohnson.nonzeroCodeWords_min
#print axioms OneAndAHalfJohnson.nonzeroCodeWords_subset
#print axioms OneAndAHalfJohnson.field_power_as_exp
#print axioms OneAndAHalfJohnson.global_tail_of_exponent
#print axioms OneAndAHalfJohnson.affineCodeWords_min_of_source
#print axioms OneAndAHalfJohnson.concrete_family_failure_sum
#print axioms OneAndAHalfJohnson.concrete_nonzero_failure_sum
#print axioms OneAndAHalfJohnson.concrete_affine_failure_sum
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.concrete_choose_le_exp
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.layer_tail_of_exponent_zero
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.layer_tail_of_exponent
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.rowSlope
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.layerExponent
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.hasDerivAt_layerExponent
#print axioms OneAndAHalfJohnson.ConcreteLogBounds.alpha_d0_first
#print axioms OneAndAHalfJohnson.ConcreteLogBounds.alpha_d0_second
#print axioms OneAndAHalfJohnson.ConcreteLogBounds.beta_wstar_first
#print axioms OneAndAHalfJohnson.ConcreteLogBounds.beta_wstar_second
#print axioms OneAndAHalfJohnson.ConcreteLogBounds.alpha_W_first
#print axioms OneAndAHalfJohnson.ConcreteLogBounds.alpha_W_second
#print axioms OneAndAHalfJohnson.ConcreteLogBounds.beta_W_first
#print axioms OneAndAHalfJohnson.ConcreteLogBounds.beta_W_second
#print axioms OneAndAHalfJohnson.ConcreteLogBounds.tau_e_first
#print axioms OneAndAHalfJohnson.ConcreteLogBounds.tau_e_second
#print axioms OneAndAHalfJohnson.ConcreteLogBounds.delta_d1_first
#print axioms OneAndAHalfJohnson.ConcreteLogBounds.delta_d1_second
#print axioms OneAndAHalfJohnson.ConcreteLogBounds.count_d0
#print axioms OneAndAHalfJohnson.ConcreteLogBounds.count_wstar
#print axioms OneAndAHalfJohnson.ConcreteLogBounds.log_two
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.hasDerivAt_bernoulliKL
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.hasDerivAt_rowProbability
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.rowProbability_monotone
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.rowProbability_mem_Ioo
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.bernoulliKL_mono
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.global_alpha_exponent
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.global_beta_exponent
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.bernoulliKL_antitone
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.short_word_upper_tail
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.incidence_upper_tail
#print axioms OneAndAHalfJohnson.sampledMean_concrete
#print axioms OneAndAHalfJohnson.exists_concrete_sampling_map
#print axioms OneAndAHalfJohnson.exists_concrete_separating_syndrome
#print axioms OneAndAHalfJohnson.finrank_inter_ker_of_surjective
#print axioms OneAndAHalfJohnson.concrete_kernel_finrank_of_Hamada
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.slope_div_survival
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.divergence_gain_of_correction
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.divergence_slope_lower
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.layerExponent_antitone
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.layer_alpha_exponent
#print axioms OneAndAHalfJohnson.ConcreteAnalyticBounds.layer_beta_exponent
#print axioms OneAndAHalfJohnson.reindexWord
#print axioms OneAndAHalfJohnson.reindexCode
#print axioms OneAndAHalfJohnson.reindexWord_dist
#print axioms OneAndAHalfJohnson.mem_reindexCode
#print axioms OneAndAHalfJohnson.reindexCode_close
#print axioms OneAndAHalfJohnson.reindexCode_far
#print axioms OneAndAHalfJohnson.reindexCode_exceptional
#print axioms OneAndAHalfJohnson.reindexCode_distance
#print axioms OneAndAHalfJohnson.reindexCode_relativeDistance
#print axioms OneAndAHalfJohnson.reindexCode_rate
#print axioms OneAndAHalfJohnson.gcd_extension_exponents
#print axioms OneAndAHalfJohnson.gcd_extension_field_size
#print axioms OneAndAHalfJohnson.gcd_extension_degree_le
#print axioms OneAndAHalfJohnson.gcd_base_dimension_ge
#print axioms OneAndAHalfJohnson.gcd_extension_degree_pos
#print axioms OneAndAHalfJohnson.SizedExtension
#print axioms OneAndAHalfJohnson.sizedExtensionAlgebra
#print axioms OneAndAHalfJohnson.sizedExtensionFiniteDimensional
#print axioms OneAndAHalfJohnson.sizedExtension_finrank
#print axioms OneAndAHalfJohnson.sizedExtension_card
#print axioms OneAndAHalfJohnson.sizedExtension_card_output_power
#print axioms OneAndAHalfJohnson.exists_sized_field_tower
#print axioms OneAndAHalfJohnson.sizedExtension_finrank_le
#print axioms OneAndAHalfJohnson.polynomial_dimension_bound_in_exponent
#print axioms OneAndAHalfJohnson.extended_incidence_dimension_bound_in_exponent
#print axioms OneAndAHalfJohnson.extended_incidence_card_bound_in_exponent
#print axioms OneAndAHalfJohnson.exists_functional_nonzero_on_family
#print axioms OneAndAHalfJohnson.independent_pairs_of_distinct_slopes
#print axioms OneAndAHalfJohnson.exists_finite_separating_syndrome
#print axioms OneAndAHalfJohnson.Geometry.Point
#print axioms OneAndAHalfJohnson.Geometry.pointFintype
#print axioms OneAndAHalfJohnson.Geometry.CodimTwo
#print axioms OneAndAHalfJohnson.Geometry.Incident
#print axioms OneAndAHalfJohnson.Geometry.incident_iff_rep_mem
#print axioms OneAndAHalfJohnson.Geometry.incident_mk_iff
#print axioms OneAndAHalfJohnson.Geometry.incidenceWord
#print axioms OneAndAHalfJohnson.Geometry.incidenceWord_eq_one
#print axioms OneAndAHalfJohnson.Geometry.incidenceWord_ne_zero
#print axioms OneAndAHalfJohnson.Geometry.support_incidenceWord
#print axioms OneAndAHalfJohnson.Geometry.incidenceSpan
#print axioms OneAndAHalfJohnson.Geometry.incidenceWord_mem_span
#print axioms OneAndAHalfJohnson.Geometry.point_card
#print axioms OneAndAHalfJohnson.Geometry.point_card_sum
#print axioms OneAndAHalfJohnson.Geometry.incidentEquiv
#print axioms OneAndAHalfJohnson.Geometry.incident_card
#print axioms OneAndAHalfJohnson.Geometry.incident_inf_iff
#print axioms OneAndAHalfJohnson.Geometry.overlap_card
#print axioms OneAndAHalfJohnson.Geometry.incidence_weight
#print axioms OneAndAHalfJohnson.Geometry.intersection_finrank_le
#print axioms OneAndAHalfJohnson.Geometry.overlap_card_le
#print axioms OneAndAHalfJohnson.Geometry.TwoSubspace
#print axioms OneAndAHalfJohnson.Geometry.TwoFrame
#print axioms OneAndAHalfJohnson.Geometry.frame_span_eq
#print axioms OneAndAHalfJohnson.Geometry.frameInSubspaceToFrame
#print axioms OneAndAHalfJohnson.Geometry.frameInSubspaceToFrame_bijective
#print axioms OneAndAHalfJohnson.Geometry.twoFrame_card
#print axioms OneAndAHalfJohnson.Geometry.twoSubspace_card_mul
#print axioms OneAndAHalfJohnson.Geometry.codimTwoEquivDualTwo
#print axioms OneAndAHalfJohnson.Geometry.codimTwo_card_mul
#print axioms OneAndAHalfJohnson.Geometry.codimTwo_card
#print axioms OneAndAHalfJohnson.Geometry.codimTwo_card_512_five
#print axioms OneAndAHalfJohnson.Geometry.seven_overlap_lt_weight
#print axioms OneAndAHalfJohnson.Geometry.incidence_rows_independent_of_card_le_eight
#print axioms OneAndAHalfJohnson.Geometry.incidenceWord_injective
#print axioms OneAndAHalfJohnson.pair_eq_of_mem
#print axioms OneAndAHalfJohnson.geometric_six_rows_independent
#print axioms OneAndAHalfJohnson.geometric_overlapping_pairs_impossible
#print axioms OneAndAHalfJohnson.shortening_word_sparse
#print axioms OneAndAHalfJohnson.shortening_contained_in_two_incidence_rows
#print axioms OneAndAHalfJohnson.geometric_pair_impossible
#print axioms OneAndAHalfJohnson.shortening_word_single
#print axioms OneAndAHalfJohnson.shortening_contained_in_one_incidence_row
#print axioms OneAndAHalfJohnson.incidence_span_distance
#print axioms OneAndAHalfJohnson.Geometry.codimTwo_nonempty
#print axioms OneAndAHalfJohnson.Geometry.incidence_arithmetic
#print axioms OneAndAHalfJohnson.Geometry.cutoff_add_three_overlap_lt_three_weight
#print axioms OneAndAHalfJohnson.Geometry.four_weight_lt_six_difference
#print axioms OneAndAHalfJohnson.Geometry.four_weight_le_three_cutoff
#print axioms OneAndAHalfJohnson.Geometry.coordinateKernel
#print axioms OneAndAHalfJohnson.Geometry.mem_coordinateKernel
#print axioms OneAndAHalfJohnson.Geometry.finrank_coordinateKernel
#print axioms OneAndAHalfJohnson.Geometry.coordinateKernel_inf
#print axioms OneAndAHalfJohnson.Geometry.tripleMask
#print axioms OneAndAHalfJohnson.Geometry.tripleExcluded
#print axioms OneAndAHalfJohnson.Geometry.tripleExcluded_card
#print axioms OneAndAHalfJohnson.Geometry.tripleExcluded_union_card
#print axioms OneAndAHalfJohnson.Geometry.tripleExcluded_union_three_card
#print axioms OneAndAHalfJohnson.Geometry.tripleSpace
#print axioms OneAndAHalfJohnson.Geometry.tripleSpace_le_common_hyperplane
#print axioms OneAndAHalfJohnson.Geometry.triple_common_hyperplane_finrank
#print axioms OneAndAHalfJohnson.Geometry.tripleSpace_pair_finrank
#print axioms OneAndAHalfJohnson.Geometry.tripleSpace_triple_finrank
#print axioms OneAndAHalfJohnson.Geometry.tripleSpace_injective
#print axioms OneAndAHalfJohnson.Geometry.triplePoints
#print axioms OneAndAHalfJohnson.Geometry.triplePoints_card
#print axioms OneAndAHalfJohnson.Geometry.triplePoints_pair_card
#print axioms OneAndAHalfJohnson.Geometry.triplePoints_triple_card
#print axioms OneAndAHalfJohnson.Geometry.triplePoints_union_card_identity
#print axioms OneAndAHalfJohnson.Geometry.triplePoints_union_card
#print axioms OneAndAHalfJohnson.Geometry.triplePoints_union_card_lt_three_weight
#print axioms OneAndAHalfJohnson.Geometry.triplePoints_union_card_512_five
#print axioms OneAndAHalfJohnson.linearIndependent_of_private_coordinates
#print axioms OneAndAHalfJohnson.exists_private_point_of_overlap_sum_lt
#print axioms OneAndAHalfJohnson.incidence_linearIndependent_of_overlap_sum_lt
#print axioms OneAndAHalfJohnson.Geometry.exists_two_functionals_kernel
#print axioms OneAndAHalfJohnson.Geometry.affineCoordinate
#print axioms OneAndAHalfJohnson.Geometry.affineCoordinates
#print axioms OneAndAHalfJohnson.Geometry.affineCoordinateSpan
#print axioms OneAndAHalfJohnson.Geometry.affineCoordinates_card_le
#print axioms OneAndAHalfJohnson.Geometry.one_mem_affineCoordinateSpan
#print axioms OneAndAHalfJohnson.Geometry.linearFunctional_mem_affineCoordinateSpan
#print axioms OneAndAHalfJohnson.Geometry.finrank_affineCoordinateSpan_pow_le
#print axioms OneAndAHalfJohnson.Geometry.finiteField_zero_indicator
#print axioms OneAndAHalfJohnson.Geometry.incidenceWord_eq_two_zero_tests
#print axioms OneAndAHalfJohnson.Geometry.incidenceWord_mem_affineCoordinateSpan_pow
#print axioms OneAndAHalfJohnson.Geometry.incidenceSpan_finrank_le_polynomial
#print axioms OneAndAHalfJohnson.Geometry.extendCode_incidenceSpan
#print axioms OneAndAHalfJohnson.Geometry.incidenceSpan_base_finrank_le_polynomial
#print axioms OneAndAHalfJohnson.Geometry.extended_incidenceSpan_finrank_le_polynomial
#print axioms OneAndAHalfJohnson.Geometry.prime_incidenceSpan_finrank_le_polynomial
#print axioms OneAndAHalfJohnson.exists_kernel_word_of_three_independent
#print axioms OneAndAHalfJohnson.Geometry.exists_small_incidence_kernel_word
#print axioms OneAndAHalfJohnson.Geometry.incidence_kernel_distance_le
#print axioms OneAndAHalfJohnson.Geometry.exists_incidence_kernel_word_512_five
#print axioms OneAndAHalfJohnson.Geometry.embed_incidenceWord
#print axioms OneAndAHalfJohnson.Geometry.incidenceWord_mem_extendCode
#print axioms OneAndAHalfJohnson.Geometry.exists_small_extended_incidence_kernel_word
#print axioms OneAndAHalfJohnson.Geometry.extended_incidence_kernel_distance_lt_three_weight
#print axioms OneAndAHalfJohnson.sum_by_weight_layers
#print axioms OneAndAHalfJohnson.sum_le_of_weight_layer_bounds
#print axioms OneAndAHalfJohnson.MainTheorems.point_base_of_AD21
#print axioms OneAndAHalfJohnson.MainTheorems.smallDistanceBase_of_AD21
#print axioms OneAndAHalfJohnson.MainTheorems.concreteTheorem_of_AD21_Hamada
#print axioms OneAndAHalfJohnson.MainTheorems.conditionalConcreteTheorem
#print axioms OneAndAHalfJohnson.MainTheorems.asymptoticConclusion_of_AD21
#print axioms OneAndAHalfJohnson.MainTheorems.mainTheorem_of_AD21
#print axioms OneAndAHalfJohnson.MainTheorems.conditionalMainTheorem
#print axioms OneAndAHalfJohnson.MainTheorems.uniqueDecodingCounterexamples_of_AD21
#print axioms OneAndAHalfJohnson.MainTheorems.actual_unique_radius_of_AD21
#print axioms OneAndAHalfJohnson.MainTheorems.shorteningStructure_of_AD21
#print axioms OneAndAHalfJohnson.MainTheorems.exists_ambient_syndrome_first_nonzero
#print axioms OneAndAHalfJohnson.MainTheorems.syndromeSeparation
#print axioms OneAndAHalfJohnson.NumericLogCertificates.exp_interval
#print axioms OneAndAHalfJohnson.NumericLogCertificates.exp_double_interval
#print axioms OneAndAHalfJohnson.exists_uniform_finite_samples
#print axioms OneAndAHalfJohnson.sampled_row_success_fraction
#print axioms OneAndAHalfJohnson.exists_sampled_uniform_amplification
#print axioms OneAndAHalfJohnson.exists_linear_uniform_amplification
#print axioms OneAndAHalfJohnson.dual_evaluation_surjective
#print axioms OneAndAHalfJohnson.dual_evaluation_fibers
#print axioms OneAndAHalfJohnson.dual_evaluation_zero_count
#print axioms OneAndAHalfJohnson.dual_evaluation_nonzero_count
#print axioms OneAndAHalfJohnson.SamplingRow
#print axioms OneAndAHalfJohnson.sampledLinearMap
#print axioms OneAndAHalfJohnson.sampled_tuple_zero_iff
#print axioms OneAndAHalfJohnson.zero_tuple_sample_count
#print axioms OneAndAHalfJohnson.sampledDualFintype
#print axioms OneAndAHalfJohnson.sampled_row_nonzero_count
#print axioms OneAndAHalfJohnson.exists_bernoulli_family_bounds
#print axioms OneAndAHalfJohnson.exists_finite_sample_family_bounds
#print axioms OneAndAHalfJohnson.sampledMean
#print axioms OneAndAHalfJohnson.exists_linear_refined_amplification
#print axioms OneAndAHalfJohnson.embedWord
#print axioms OneAndAHalfJohnson.extendCode
#print axioms OneAndAHalfJohnson.supportedCode
#print axioms OneAndAHalfJohnson.coefficient_mem_base
#print axioms OneAndAHalfJohnson.extendCode_inf_supported
#print axioms OneAndAHalfJohnson.finrank_extendCode
#print axioms OneAndAHalfJohnson.extendCode_mono
#print axioms OneAndAHalfJohnson.extendCode_span
#print axioms OneAndAHalfJohnson.shortened_extendCode_le_span
#print axioms OneAndAHalfJohnson.shortened_extendCode_le_singleton
#print axioms OneAndAHalfJohnson.shortened_extendCode_le_pair
#print axioms OneAndAHalfJohnson.three_sets_card_identity
#print axioms OneAndAHalfJohnson.three_sets_sdiff_subset_of_overlapping_pairs
#print axioms OneAndAHalfJohnson.overlapping_pairs_card_bound
#print axioms OneAndAHalfJohnson.overlapping_pairs_impossible
#print axioms OneAndAHalfJohnson.sparse_representation_unique
#print axioms OneAndAHalfJohnson.three_or_four_rows_not_two
#print axioms OneAndAHalfJohnson.sparse_pair_must_overlap
#print axioms OneAndAHalfJohnson.exists_common_sparse_support
#print axioms OneAndAHalfJohnson.two_sets_card_bound
#print axioms OneAndAHalfJohnson.exists_common_single_support
#print axioms OneAndAHalfJohnson.exists_dense_translate
#print axioms OneAndAHalfJohnson.exists_dense_subfield_line
#print axioms OneAndAHalfJohnson.exists_dense_subfield_line_coefficients
#print axioms OneAndAHalfJohnson.Far.smul_nonzero
#print axioms OneAndAHalfJohnson.far_smul_nonzero_iff
#print axioms OneAndAHalfJohnson.zero_not_mem_exceptional_of_far
#print axioms OneAndAHalfJohnson.exists_subfield_exceptional_reduction
#print axioms OneAndAHalfJohnson.SubspacePolynomial.rootProduct
#print axioms OneAndAHalfJohnson.SubspacePolynomial.rootProduct_monic
#print axioms OneAndAHalfJohnson.SubspacePolynomial.rootProduct_eval_eq_zero
#print axioms OneAndAHalfJohnson.SubspacePolynomial.rootProduct_natDegree
#print axioms OneAndAHalfJohnson.SubspacePolynomial.rootProduct_injective
#print axioms OneAndAHalfJohnson.SubspacePolynomial.QPowerSupport
#print axioms OneAndAHalfJohnson.SubspacePolynomial.natDegree_sub_le_of_top_coefficients
#print axioms OneAndAHalfJohnson.SubspacePolynomial.subspace_eq_of_top_two_coefficients
#print axioms OneAndAHalfJohnson.SubspacePolynomial.geometry_card_cast_eq_zero
#print axioms OneAndAHalfJohnson.SubspacePolynomial.rootProduct_derivative
#print axioms OneAndAHalfJohnson.SubspacePolynomial.rootProduct_lagrange_denominator
#print axioms OneAndAHalfJohnson.SubspacePolynomial.sum_eval_eq_linear_coeff_mul
#print axioms OneAndAHalfJohnson.SubspacePolynomial.moment
#print axioms OneAndAHalfJohnson.SubspacePolynomial.moment_lt_card
#print axioms OneAndAHalfJohnson.SubspacePolynomial.moment_recurrence
#print axioms OneAndAHalfJohnson.SubspacePolynomial.moment_middle_eq_zero
#print axioms OneAndAHalfJohnson.SubspacePolynomial.moment_high_eq_neg_coeff
#print axioms OneAndAHalfJohnson.SubspacePolynomial.rootProduct_tail_bound
#print axioms OneAndAHalfJohnson.SubspacePolynomial.moment_card_sub_one
#print axioms OneAndAHalfJohnson.SubspacePolynomial.moment_two_card_sub_qpow_sub_one
#print axioms OneAndAHalfJohnson.SubspacePolynomial.rootProduct_distinguished_moments
#print axioms OneAndAHalfJohnson.SubspacePolynomial.rootProduct_separable
#print axioms OneAndAHalfJohnson.SubspacePolynomial.rootProduct_coeff_zero
#print axioms OneAndAHalfJohnson.SubspacePolynomial.rootProduct_coeff_one_ne_zero
#print axioms OneAndAHalfJohnson.SubspacePolynomial.qPolynomial
#print axioms OneAndAHalfJohnson.SubspacePolynomial.qPolynomial_coeff
#print axioms OneAndAHalfJohnson.SubspacePolynomial.qPolynomial_ne_zero
#print axioms OneAndAHalfJohnson.SubspacePolynomial.qPolynomial_support
#print axioms OneAndAHalfJohnson.SubspacePolynomial.qPolynomial_natDegree_le
#print axioms OneAndAHalfJohnson.SubspacePolynomial.qEvaluation
#print axioms OneAndAHalfJohnson.SubspacePolynomial.qEvaluation_apply
#print axioms OneAndAHalfJohnson.SubspacePolynomial.basisEvaluation
#print axioms OneAndAHalfJohnson.SubspacePolynomial.exists_nonzero_annihilator_coefficients
#print axioms OneAndAHalfJohnson.SubspacePolynomial.rootProduct_qPowerSupport
#print axioms OneAndAHalfJohnson.SubspacePolynomial.qPowerSupport_two_ext
#print axioms OneAndAHalfJohnson.SubspacePolynomial.rootProduct_top_two_determine_subspace
#print axioms OneAndAHalfJohnson.exists_avoiding_supercode_step
#print axioms OneAndAHalfJohnson.exists_avoiding_supercode
#print axioms OneAndAHalfJohnson.exists_avoiding_supercode_of_pow_bound
#print axioms OneAndAHalfJohnson.hammingDist_sub_eq_norm
#print axioms OneAndAHalfJohnson.close_of_equal_syndrome
#print axioms OneAndAHalfJohnson.close_of_normalized_syndrome
#print axioms OneAndAHalfJohnson.card_exceptional_ge_of_syndromes
#print axioms OneAndAHalfJohnson.far_of_syndrome_exclusion
#print axioms OneAndAHalfJohnson.SyndromeConstruction.mem_line_iff
#print axioms OneAndAHalfJohnson.SyndromeConstruction.lineSum
#print axioms OneAndAHalfJohnson.SyndromeConstruction.incidence_lineSum
#print axioms OneAndAHalfJohnson.SyndromeConstruction.weightedSum
#print axioms OneAndAHalfJohnson.SyndromeConstruction.momentFunctional
#print axioms OneAndAHalfJohnson.SyndromeConstruction.momentFunctional_incidence
#print axioms OneAndAHalfJohnson.SyndromeConstruction.exponentZero
#print axioms OneAndAHalfJohnson.SyndromeConstruction.exponentOne
#print axioms OneAndAHalfJohnson.SyndromeConstruction.exponentTwo
#print axioms OneAndAHalfJohnson.SyndromeConstruction.exponents_pos
#print axioms OneAndAHalfJohnson.SyndromeConstruction.syndromeMap
#print axioms OneAndAHalfJohnson.SyndromeConstruction.syndromeMap_incidence
#print axioms OneAndAHalfJohnson.SyndromeConstruction.affine_coefficients_injective
#print axioms OneAndAHalfJohnson.SyndromeConstruction.independent_scaled_affine_pairs
#print axioms OneAndAHalfJohnson.SyndromeConstruction.syndromeMap_incidence_fst_ne_zero
#print axioms OneAndAHalfJohnson.SyndromeConstruction.syndromeMap_incidence_ne_zero
#print axioms OneAndAHalfJohnson.SyndromeConstruction.syndromeMap_incidence_pair_independent
#print axioms OneAndAHalfJohnson.SyndromeConstruction.exists_separating_syndrome_of_tower
#print axioms OneAndAHalfJohnson.hammingNorm_smul_nonzero
#print axioms OneAndAHalfJohnson.syndrome_normalize
#print axioms OneAndAHalfJohnson.card_exceptional_ge_of_syndrome_slopes
#print axioms OneAndAHalfJohnson.slopes_injective_of_pairwise_independent
#print axioms OneAndAHalfJohnson.card_exceptional_ge_of_independent_syndromes
#print axioms OneAndAHalfJohnson.Targets.baseLength
#print axioms OneAndAHalfJohnson.Targets.incidenceWeight
#print axioms OneAndAHalfJohnson.Targets.SmallDistanceBase
#print axioms OneAndAHalfJohnson.Targets.ShorteningStructure
#print axioms OneAndAHalfJohnson.Targets.extendedIncidence
#print axioms OneAndAHalfJohnson.Targets.SyndromeSeparation
#print axioms OneAndAHalfJohnson.Targets.ConditionalMainTheorem
#print axioms OneAndAHalfJohnson.Targets.ConditionalSmallDistanceBase
#print axioms OneAndAHalfJohnson.Targets.ConditionalShorteningStructure
#print axioms OneAndAHalfJohnson.Targets.ConditionalConcreteTheorem
#print axioms OneAndAHalfJohnson.Targets.uniqueDecoding_of_main
#print axioms OneAndAHalfJohnson.Targets.lowWeightCutoff
#print axioms OneAndAHalfJohnson.Targets.AD21LowWeight
#print axioms OneAndAHalfJohnson.Targets.HamadaBinaryRank
#print axioms OneAndAHalfJohnson.Targets.AsymptoticConclusion
#print axioms OneAndAHalfJohnson.Targets.MainTheorem
#print axioms OneAndAHalfJohnson.Targets.UniqueDecodingCounterexamples
#print axioms OneAndAHalfJohnson.Targets.ConcreteTheorem
#print axioms OneAndAHalfJohnson.johnson_lt_gamma
#print axioms OneAndAHalfJohnson.gamma_lt_distance
#print axioms OneAndAHalfJohnson.amplify_zero
#print axioms OneAndAHalfJohnson.amplify_mono
#print axioms OneAndAHalfJohnson.johnson_lt_half_iff
#print axioms OneAndAHalfJohnson.concrete_johnson_upper
#print axioms OneAndAHalfJohnson.johnson_mono
#print axioms OneAndAHalfJohnson.measure_abs_gt_le_of_subgaussian
#print axioms OneAndAHalfJohnson.measure_average_deviation_le
#print axioms OneAndAHalfJohnson.exists_uniform_average_concentration
#print axioms OneAndAHalfJohnson.choose_le_exp_log_bound
#print axioms OneAndAHalfJohnson.supported_family_card_le
#print axioms OneAndAHalfJohnson.weight_layer_card_le
#print axioms OneAndAHalfJohnson.affineCodeWords
#print axioms OneAndAHalfJohnson.affineCodeWords_card
#print axioms OneAndAHalfJohnson.affineCodeWords_separated
#print axioms OneAndAHalfJohnson.affineCodeWords_layer_card_le
